[package]
name = "sheepy-world"
version = "0.1.0"
description = "Sheepy World: A Cheeky Tale"
authors = ["Gonçalo Terroso"]
edition = "2021"

[lib]
name = "sheepy_world_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
